### ISSUE TITLE
 ZCE LLVM 14: LUI Compressed regression ??

### ISSUE THREAD

**Issue by abukharmeh** [plctlab/llvm-project#41]
Hi, 
I am currently evaluating the behavior of latest Zce LLVM compiler, and noticed that the compiler stopped inferring c.lui as often as it was, resulting in worsening the code size in many instances. 

For example, the following assembly was generated when compiling statemate benchmark from Embench: 

![image](https://user-images.githubusercontent.com/24764074/167259849-221734be-1492-4498-9ef8-cb426d7ca417.png)

I wonder why  ? 

Thanks,
Ibrahim.

**Comment by Xinlong-Wu** [comment]
I've had a cursory look at the current code and I don't think this issue should be happening. I will try to recreate it. 
Can you give me the commit id of two compilers?

**Comment by abukharmeh** [comment]
I am compiling with the head of the tree of llvm 14 zce branch with and without zce (142ad832fac0da825e4cd4496716a964fd4e4014). 

For Zce screenshot on the left, I compiled with the following arguments
`'-menable-experimental-extensions','-march=rv32ima_zca0p70_zcb0p70_zcmb0p70_zcmp0p70'`
For mainline screenshot on the right, I compiled with the following arguments
`'-march=rv32imac'`

**Comment by Xinlong-Wu** [comment]
The problem has been identified, you can try to disassemble `libstatemate.o` and see the difference.

This is because part of the `c.lui` instruction optimization (eg. global variable) is handled by the linker. When `C ext` is used, the argument `RVC` is passed via the `e_flag` of the elf file. But `zca` extension does not pass similar information.

![image](https://user-images.githubusercontent.com/43398706/167284838-ed277cfa-c1aa-48bf-90fc-a51590d76b73.png)

I will add a new `e_flag` like `RVZCA` to handle that.

**Comment by abukharmeh** [comment]
Aha, that make sense, thank you very much. That actually being said, I think we should not allow linking files that have RVC flag set with the new flag as that will cause confusion !

**Comment by Xinlong-Wu** [comment]
To some extent, RVC flag is necessary for elf files. cuz the address of variables can't determine by clang compiler before linking. That means we can only decide whether convert `lui` to `c.lui` in the linker. That's why we need RVC flag.

for Zca ext, we have two ways to enable optimization `lui` inst.

1. let the compiler also generate RVC flag when Zce is enabled. but the llvm-objdump will read the RVC flag and set `+c` into target feature automatically. so I think it may cause potential errors in llvm-objdump if Zca generate RVC flag 

2. Generate new RVZCA flag for Zca ext. To be honest,  RVZCA and RVC have exactly the same effect. what we do in the linker is replace the code `hasExtC` with `(hasExtC || hasExtZca)`. It may cause confusion, but it will not cause errors at least.

we have committed a patch as I have said in a second way for temporary. You can check it by 2f4222dfc16161e7f39c80b26fdc9280dd9a1051

**Comment by abukharmeh** [comment]
I think I prefer to have a separate flag for Zca, because then if somebody tried to link C files with Zca files, we can error out as they are not compatible because of the change of the double float encoding meaning ? 

I know that they take the allocation of flags in the elf header fairly seriously and I am not sure if they will allocate us flag for this ! Perhaps @tariqkurd-repo could comment on that ?

**Comment by tariqkurd-repo** [comment]
There certainly needs to be a compatibility check. Who allocates flags in the elf header?

**Comment by abukharmeh** [comment]
I saw this earlier https://lists.riscv.org/g/tech-toolchain-runtime/topic/80580826?p=Created%2C%2C%2C20%2C1%2C0%2C0%3A%3Arecentpostdate%2Fsticky%2C%2C%2C20%2C2%2C20%2C80580826 and thought you might know.
I could send an email to the mailing list, likely Jim Wilson will be able to comment on that !

**Comment by abukharmeh** [comment]
@jim-wilson I wonder if you have any comments on this issue ?

**Comment by abukharmeh** [comment]
Zc* support did not land in any shipped toolchain. Zca defines a subset of the C extension where all compressed float instructions are removed. 

Its not completely clear for me weather the C ELF flag should be set when targetting Zca or not. If the C flag only indicate 2-byte alignment, then we should probably set it. However, It appears that the compiler is using that flag to indicate to the linker that it can perform various compressed linker relaxations, perhaps C attribute should be used to indicate that ?

There exist no conflict between the relaxations that the linker can perform for Zca and C extension, we just need to find a way to prevent the linker linking C extension elf files with Zca files as float could mean something else. 

Maybe all we need is a new attribute, and make sure that C and Zca attributes are mutually exclusive. 

I will write an email to the psABI mailing list with short description of the issue.

**Comment by abukharmeh** [comment]
@kito-cheng  Thank you very much. So I understand that we should really set EF_RISCV_RVC  flag for Zc* extension as ideally its used to indicate 2-byte alignment, and we should use Tag_RISCV_arch to check for compatibility and what linker relaxations we are performing !

**Comment by abukharmeh** [comment]
```
Here is another problem behind the solution, the ELF attribute isn't
mandatory for current psABI spec, so that would be TODO item for psABI
spec, but I think that's wound be big problem in current open source
toolchain since we already default to emit those attribute for both
LLVM and GCC compiler.
```
So our working assumption should be that psABI TG will make them mandatory at some point soon, and we dont need to worry about that  ?

**Comment by Xinlong-Wu** [comment]
Jiawei @pz9115 will replace Sinan for the GCC updates of Zc

**Comment by pz9115** [comment]
We had use `EF_RISCV_RVC`  in binutils, when reuse instruction in `c` extension, this will to enable the compress intrustion generate correctly. The whole Zc* extension can be devided in two part, one (`Zca` `Zcf`)  reuse `c` extension instructions,  another part (`Zcb Zcm*`) are independent. For the reuse part, it need to submit the feature in origin `c` elf flag.

**Comment by kito-cheng** [comment]
> So our working assumption should be that psABI TG will make them mandatory at some point soon, and we dont need to worry about that ?

Yes :)
